export const types = {
    FETCH_JOKE: 'FETCH_JOKE',
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    FETCH_JOKES_BY_CATEGORY: 'FETCH_JOKES_BY_CATEGORY',
    FETCH_SEARCH_RESULT: 'FETCH_SEARCH_RESULT',
    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    EDIT_FAVORITE: 'EDIT_FAVORITE',
    DELETE_FAVORITE: 'DELETE_FAVORITE'
}